version: "2"
services:
  geoslicerbase-windows:
    image: geoslicerbase-windows:latest
    build:
      context: .
      dockerfile: tools/docker/windows.Dockerfile
    volumes:
      - .:c:/geoslicerbase/
      - ~/.oci/:C:/Users/ContainerAdministrator/.oci/
      - ~/.ssh/:C:/Users/ContainerAdministrator/.ssh/
    storage_opt:
      size: '60G'
  geoslicerbase-linux:
    image: geoslicerbase-linux:latest
    build:
      context: .
      dockerfile: tools/docker/centos.Dockerfile
    volumes:
      - .:/geoslicerbase
      - ~/.ssh/:/root/.ssh/
      - ~/.oci/:/root/.oci/
    storage_opt:
      size: '60G'