version: "2"
services:
  geoslicerbase-windows:
    image: geoslicerbase-windows:latest
    build:
      context: .
      dockerfile: tools/docker/windows.Dockerfile
    volumes:
      - .:c:/geoslicerbase/
    storage_opt:
      size: '160G'
    mem_limit: 24GB
    environment:
      - USING_DOCKER=1
  geoslicerbase-linux:
    image: geoslicerbase-linux:latest
    build:
      context: .
      dockerfile: tools/docker/centos.Dockerfile
    volumes:
      - .:/geoslicerbase
    storage_opt:
      size: '160G'
    mem_limit: 24GB
    environment:
      - USING_DOCKER=1