version: "3"
services:
  geoslicerbase-windows:
    image: geoslicerbase-windows:latest
    build:
      context: .
      dockerfile: tools/docker/windows.Dockerfile
      target: image-prod
    volumes:
      - ~/.ssh:c:/Users/ContainerAdministrator/.ssh
    storage_opt:
      size: '30G'
  geoslicerbase-windows-dev:
    image: geoslicerbase-windows-dev:latest
    build:
      context: .
      dockerfile: tools/docker/windows.Dockerfile
      target: image-dev
    volumes:
      - .:c:/geoslicerbase/
      - ~/.ssh:c:/Users/ContainerAdministrator/.ssh
    storage_opt:
      size: '30G'
  geoslicerbase-ubuntu:
    image: geoslicerbase-ubuntu:latest
    build:
      context: .
      dockerfile: tools/docker/ubuntu.Dockerfile
      target: image-prod
    volumes:
      - ~/.ssh:c:/Users/ContainerAdministrator/.ssh
    storage_opt:
      size: '30G'
  geoslicerbase-ubuntu-dev:
    image: geoslicerbase-ubuntu-dev:latest
    build:
      context: .
      dockerfile: tools/docker/ubuntu.Dockerfile
      target: image-dev
    volumes:
      - .:/geoslicerbase
      - ~/.ssh:/root/.ssh
    storage_opt:
      size: '30G'