pipeline {
    agent any
    options { 
        skipDefaultCheckout() 
        throttle(['base_build'])
    }
    parameters {
        string(name: 'SLICER_COMMIT', defaultValue: "", description: 'The LTrace/Slicer.git commit hash to build with')
        choice(name: 'PLATFORM', choices: ['Windows', 'Linux', 'Both'], description: 'Select the desired Operational System to generate the application.')
        choice(name: 'BUILD_TYPE', choices: ['Release', 'Debug'], description: 'Select the build type.')
        choice(name: 'THREADS', choices: ['32', '16', '8', '4', '2', '1'], description: 'Select the thread\'s number to be used to compile.')
    }
    environment {
        OCI_DOCKER_REGISTRY_TOKEN_ID     = credentials("oci_docker_registry_token_id")
        OCI_DOCKER_REGISTRY_TOKEN_PASSWORD = credentials("oci_docker_registry_token_password")
    }
    stages {
        stage("Parallel Stage") {
            options { skipDefaultCheckout() }
            when {
                allOf {
                    triggeredBy cause: 'UserIdCause'
                }
            }
            parallel {
                stage("Windows") {
                    options { skipDefaultCheckout() }
                    when {
                        beforeAgent true;
                        anyOf {
                                expression { return "${params.PLATFORM}" == "Windows"; } 
                                expression { return "${params.PLATFORM}" == "Both"; } 
                        }
                    }
                    agent {
                            label "windows"
                    }
                    stages {
                        stage('Build Image [Windows]') {
                            options {
                                timeout(time: 120, unit: "MINUTES")
                            }
                            steps {
                                cleanWs()
                                checkout scm
                                powershell 'docker login gru.ocir.io -u "$env:OCI_DOCKER_REGISTRY_TOKEN_ID" -p "$env:OCI_DOCKER_REGISTRY_TOKEN_PASSWORD"'
                                powershell '''
                                    docker-compose build geoslicerbase-windows
                                '''
                            }
                            post {
                                always {
                                    powershell "docker image prune -f"
                                }
                            }
                        }
                        stage('Build & Pack [Windows]') {
                            options {
                                timeout(time: 15, unit: "HOURS")
                            }
                            steps {                        
                                powershell '''
                                    docker-compose up -d geoslicerbase-windows --wait
                                    docker-compose exec -T geoslicerbase-windows powershell ./geoslicerbase/tools/update_cmakelists_content.ps1 -commit "${env:SLICER_COMMIT}"
                                    docker-compose exec -T geoslicerbase-windows cmake -G "Visual Studio 16 2019" -A x64 -DQt5_DIR:PATH=C:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5 -S C:/geoslicerbase -B C:/gsb
                                    docker-compose exec -T geoslicerbase-windows cmake --build C:/gsb --config Release -j "${env:THREADS}"
                                    docker-compose exec -T geoslicerbase-windows msbuild C:/gsb/Slicer-Build/PACKAGE.vcxproj /p:Configuration=Release /m:"${env:THREADS}"
                                    docker-compose exec -T geoslicerbase-windows choco install python --version=3.9.13 -y
                                    docker-compose exec -T geoslicerbase-windows python -m pip install --upgrade pip==22.0.2
                                    docker-compose exec -T geoslicerbase-windows python -m pip install -r ./geoslicerbase/tools/requirements.txt
                                    docker-compose exec -T geoslicerbase-windows python ./geoslicerbase/tools/build_and_pack.py --source ./geoslicerbase --only-export --avoid-long-path
                                '''
                            }
                            post {
                                always {
                                    powershell "docker-compose down --remove-orphans -v"
                                    powershell "docker system prune --force --filter 'until=3h'"
                                    powershell "docker volume prune --force"
                                    archiveArtifacts artifacts: 'tools/docker/*.log', fingerprint: true, allowEmptyArchive: true
                                }
                            }
                        }
                    }
                    post {
                        // Clean after build
                        always {
                            cleanWs(cleanWhenNotBuilt: false,
                                    deleteDirs: true,
                                    disableDeferredWipeout: true,
                                    notFailBuild: true,
                                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                                            [pattern: '.propsfile', type: 'EXCLUDE']])
                        }
                    }
                }
                stage("Linux") {
                    options { skipDefaultCheckout() }
                    when {
                        beforeAgent true;
                        anyOf {
                                expression { return "${params.PLATFORM}" == "Linux"; } 
                                expression { return "${params.PLATFORM}" == "Both"; } 
                        }
                    }
                    agent {
                            label "linux"
                    }
                    stages {
                        stage('Build Image [Linux]') {
                            options {
                                timeout(time: 120, unit: "MINUTES")
                            }
                            steps {
                                cleanWs()
                                checkout scm  
                                sh '''
                                    docker-compose build geoslicerbase-linux
                                   '''
                            }
                            post {
                                always {
                                    sh "docker image prune -f"
                                }
                            }
                        }
                        stage('Build & Pack [Linux]') {
                            options {
                                timeout(time: 15, unit: "HOURS")
                            }
                            steps {                        
                                sh '''
                                    docker-compose up -d geoslicerbase-linux --wait
                                    docker-compose exec -T geoslicerbase-linux python /geoslicerbase/tools/update_cmakelists_content.py --commit "${SLICER_COMMIT}"
                                    docker-compose exec -T geoslicerbase-linux python /geoslicerbase/tools/build_and_pack.py --source /geoslicerbase --avoid-long-path --jobs "${THREADS}" --type "${BUILD_TYPE}"
                                '''
                            }
                            post {
                                always {
                                    sh "docker-compose down --remove-orphans -v"
                                    sh "docker system prune --force --filter 'until=3h'"
                                    sh "docker volume prune --force"
                                    archiveArtifacts artifacts: 'tools/docker/*.log', fingerprint: true, allowEmptyArchive: true
                                }
                            }
                        }
                    }
                    post {
                        // Clean after build
                        always {
                            cleanWs(cleanWhenNotBuilt: false,
                                    deleteDirs: true,
                                    disableDeferredWipeout: true,
                                    notFailBuild: true,
                                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                                            [pattern: '.propsfile', type: 'EXCLUDE']])
                        }
                    }
                }
            }
        }
    }
}

